// // /* =============================================================================
//    PLACEHOLDERS TO FILL BEFORE SHIPPING
//    -----------------------------------------------------------------------------
//    1. ServBeyond RAG bullet: [ADD NUMBER] manual touchpoints, [ADD HOURS] per week
//       (capture at the Week 8 MVP review, then replace).
//    2. Runara bullet 1 (optional): [ADD X]x throughput vs baseline. Remove the
//       clause if you do not have a confirmed number, the technical depth holds it up.
//    3. Runara title + employment type: confirm exact title (I used
//       "LLM Inference Engineer") and whether it was an internship, contract, or
//       research engagement.
//    4. ASSET FILES NEEDED: add two logos to ../assets/
//          - servbeyond_logo.png
//          - runara_logo.png
//       The two imports below will break the build until those files exist.
//    ============================================================================= */

import svipes_logo from "../assets/svipes_logo.jpg";
import xelp_logo from "../assets/xelp_logo.jpg";
import iith from "../assets/iith.jpg";
import umd_logo from "../assets/umd_logo.png";
import ou_logo from "../assets/ou_logo.png";
import suntek_corp from "../assets/suntek_corp.jpg";
import servbeyond_logo from "../assets/servbeyond_logo.jpg";
import runara_logo from "../assets/stealth_ai_logo.jpg";

import ActivityLogger from "../assets/ActivityLogger.jpg";
import MeetSpace from "../assets/MeetSpace.png";
import collabDraw from "../assets/collabDraw.png";
import aIChatbot from "../assets/aIChatbot.png";
import reportGen from "../assets/reportGen.png";
import terrapinEvents from "../assets/terrapinEvents.png";
import videoAnalytics from "../assets/videoAnalytics.png";
import jobTracker from "../assets/jobTracker.png";
import carebridge from "../assets/carebridge.png";
import text_to_image from "../assets/text_to_image.png";

// WebP variants (generated by scripts/convert-webp.mjs); originals above stay as fallback.
import svipes_logo_webp from "../assets/svipes_logo.webp";
import xelp_logo_webp from "../assets/xelp_logo.webp";
import iith_webp from "../assets/iith.webp";
import umd_logo_webp from "../assets/umd_logo.webp";
import ou_logo_webp from "../assets/ou_logo.webp";
import suntek_corp_webp from "../assets/suntek_corp.webp";
import servbeyond_logo_webp from "../assets/servbeyond_logo.webp";
import runara_logo_webp from "../assets/stealth_ai_logo.webp";

import ActivityLogger_webp from "../assets/ActivityLogger.webp";
import MeetSpace_webp from "../assets/MeetSpace.webp";
import collabDraw_webp from "../assets/collabDraw.webp";
import aIChatbot_webp from "../assets/aIChatbot.webp";
import reportGen_webp from "../assets/reportGen.webp";
import terrapinEvents_webp from "../assets/terrapinEvents.webp";
import videoAnalytics_webp from "../assets/videoAnalytics.webp";
import jobTracker_webp from "../assets/jobTracker.webp";
import carebridge_webp from "../assets/carebridge.webp";
import text_to_image_webp from "../assets/text_to_image.webp";

export const HERO_CONTENT = `I build AI systems and the infrastructure that runs them. My recent work spans LLM inference optimization, retrieval augmented generation, and multi agent workflows, backed by 2+ years shipping production web, mobile, and cloud native systems.
I care about latency, throughput, and reliability, and I like owning products end to end, from frontend and backend APIs down to GPU level model serving and deployment.`;

export const experiences = [
  {
    title: "Enterprise AI and Platform Intern",
    company_name: "ServBeyond Solutions",
    icon: servbeyond_logo,
    icon_webp: servbeyond_logo_webp,
    iconBg: "#fff",
    date: "June 2026 - Present",
    website: "https://www.servbeyond.com/",
    points: [
      "Built and shipped a retrieval augmented generation assistant over internal company documentation using LangChain and OpenAI APIs, automating [ADD NUMBER] manual support touchpoints and saving an estimated [ADD HOURS] per week across the team.",
      "Developed Salesforce and ServiceNow proof of concepts with REST and SOAP API integrations feeding a normalized AWS data layer.",
      "Designed reusable UI component libraries and demo grade prototypes used in presales engagements with enterprise clients.",
    ],
  },
  {
    title: "LLM Inference Engineer",
    company_name: "Runara",
    icon: runara_logo,
    icon_webp: runara_logo_webp,
    iconBg: "#fff",
    date: "March 2026 - May 2026",
    website: "",
    points: [
      "Optimized large language model inference serving across vLLM, SGLang, and TensorRT LLM, profiling throughput and latency on RTX Pro 6000 Blackwell GPUs to maximize tokens per second under production style load [achieving [ADD X]x higher throughput vs the baseline serving stack].",
      "Implemented post training quantization with GPTQ, AWQ, and NVFP4 and added speculative decoding to shrink memory footprint and accelerate token generation while holding accuracy steady.",
      "Engineered CUDA kernel fusion and KV cache optimizations to cut per request overhead on hot inference paths.",
      "Built telemetry and observability pipelines for inference workloads and orchestrated evaluation and benchmarking flows with LangChain and LangGraph.",
    ],
  },
  {
    title: "Full Stack Developer",
    company_name: "Svipes",
    icon: svipes_logo,
    icon_webp: svipes_logo_webp,
    iconBg: "#383E56",
    date: "July 2024 - December 2024",
    website: "https://svipes.com/",
    points: [
      "Built 50+ cross platform mobile screens with React Native and Redux Toolkit, shipping production ready UI features end to end.",
      "Refactored the video module with asynchronous loading and caching strategies, reducing playback stutter by 70% and load time by 1.3 seconds.",
      "Designed a scalable UI component library from Figma specs, improving code maintainability and team velocity.",
    ],
  },
  {
    title: "Software Developer",
    company_name: "Xelpmoc Design and Tech Limited",
    icon: xelp_logo,
    icon_webp: xelp_logo_webp,
    iconBg: "#fff",
    date: "November 2022 - April 2024",
    website: "https://www.xelpmoc.in/",
    points: [
      "Optimized SQL queries and introduced Redis caching by restructuring joins and indexing high traffic tables, cutting response time from 75 seconds to under 10 seconds and roughly quadrupling API throughput.",
      "Built a real time interview system with WebRTC and Socket.IO supporting 100+ concurrent video sessions at under 200ms latency.",
      "Delivered 30+ React Native screens for a blockchain credentials wallet, integrating 15+ webhooks for real time data sync across iOS and Android.",
      "Led architecture for a tourism services platform on React and React Native, reducing production defects by 40% and improving delivery velocity by 25%.",
      "Shipped twin production apps for a senior living network serving 50+ residents and 20+ staff, improving operational coordination by 35% through real time sync and notification workflows.",
    ],
  },
  {
    title: "Summer Software Intern",
    company_name: "IIIT Hyderabad",
    icon: iith,
    icon_webp: iith_webp,
    iconBg: "#fff",
    date: "June 2022 - August 2022",
    website: "https://indicwiki.iiit.ac.in/",
    points: [
      "Automated multilingual data extraction with Python and Selenium and fine tuned NLP models for regional language emotion classification, improving accuracy by 15%.",
      "Contributed to research that resulted in an accepted publication at an international NLP conference.",
    ],
  },
  {
    title: "Academic Mentor (Data Structures and OOP)",
    company_name: "Suntek Organization",
    icon: suntek_corp,
    icon_webp: suntek_corp_webp,
    iconBg: "#383E56",
    date: "2021 - 2022",
    website:
      "https://www.linkedin.com/company/suntek-corp-solutions-pvt-ltd/?originalSubdomain=at",
    points: [
      "Mentored 15+ undergraduates one on one in data structures and object oriented programming, covering recursion, trees, graphs, hashing, and complexity tradeoffs.",
      "Ran weekly coding workshops and problem solving sessions to build a collaborative, peer driven learning environment.",
    ],
  },
];

export const education = [
  {
    company_name: "University of Maryland, College Park",
    title: "Master of Engineering, Computer Software Engineering",
    icon: umd_logo,
    icon_webp: umd_logo_webp,
    iconBg: "#383E56",
    date: "January 2025 - December 2026",
    website: "https://umd.edu/",
    points: [
      "GPA 3.5. Completing a Graduate Certificate in Cloud Engineering alongside the degree.",
      "Coursework in Cloud Computing, Virtualization, Cloud Security, and Software Design, with hands on Docker and Kubernetes.",
      "Focused on scalable software architecture, backend systems, and performance oriented engineering.",
      "Interested in applied AI systems, LLM serving infrastructure, and production cloud native workflows.",
    ],
  },
  {
    company_name: "Osmania University",
    title: "Bachelor of Engineering, Computer Science",
    icon: ou_logo,
    icon_webp: ou_logo_webp,
    iconBg: "#383E56",
    date: "January 2019 - December 2023",
    website: "https://www.osmania.ac.in/",
    points: [
      "Strong foundation in data structures, algorithms, and system design.",
      "In depth study of operating systems, computer networks, and database management systems.",
      "Advanced programming including OOP, design patterns, and software architecture.",
    ],
  },
];

export const projects = [
  {
    name: "CareBridge AI",
    description:
      "AI powered care transition platform that turns discharge PDFs into structured clinical data, multi agent validation outputs, and actionable care plans. Built with FastAPI, React, PostgreSQL, and Google ADK, with confidence threshold guardrails to catch post discharge risks earlier and improve reliability.",
    tags: [
      { name: "FastAPI", color: "text-green-600" },
      { name: "Google ADK", color: "text-purple-600" },
      { name: "AI Agents", color: "text-blue-600" },
      { name: "React", color: "text-blue-600" },
    ],
    categories: ["AI", "Healthcare", "Full Stack"],
    featured: true,
    image: carebridge,
    image_webp: carebridge_webp,
    metric: "Earlier risk detection",
    source_code_link: "https://github.com/vineetagarwal54/carebridge-ai",
  },
  {
    name: "AI Repository Analyzer",
    description:
      "Multi agent code analysis platform that ingests GitHub repositories or ZIP files and returns architecture insights, API understanding, database analysis, and context aware Q and A. Built with FastAPI, LangChain, AutoGen, FAISS, and OpenAI, using a RAG layer over the codebase and specialized SDE, PM, and QA agents.",
    tags: [
      { name: "AutoGen", color: "text-purple-600" },
      { name: "LangChain", color: "text-teal-600" },
      { name: "RAG", color: "text-green-600" },
      { name: "FAISS", color: "text-blue-600" },
    ],
    categories: ["AI", "Backend", "Full Stack"],
    featured: true,
    image: reportGen,
    image_webp: reportGen_webp,
    metric: "3 specialized agents",
    source_code_link: "https://github.com/vineetagarwal54/RepoResearchAI",
  },
  {
    name: "AWS Video Analytics Streaming Platform",
    description:
      "Cloud native, serverless analytics platform on AWS using Lambda, EKS, S3, DynamoDB, SQS, API Gateway, AppSync, and CloudFormation. Microservices auto scale from 2 to 10 pods behind a load balancer with CloudFront delivery, infrastructure as code, and a GitHub Actions CI/CD pipeline that passed security scanning with zero critical vulnerabilities.",
    tags: [
      { name: "AWS Lambda", color: "text-orange-500" },
      { name: "EKS", color: "text-blue-600" },
      { name: "Serverless", color: "text-teal-600" },
      { name: "CloudFormation", color: "text-purple-600" },
    ],
    categories: ["Cloud", "Backend", "Infrastructure"],
    featured: true,
    image: videoAnalytics,
    image_webp: videoAnalytics_webp,
    metric: "0 critical vulnerabilities",
    source_code_link:
      "https://github.com/Divyesh4683/AWS-Video-Analytics-Streaming-Dashboard",
  },
  {
    name: "Text to Image Llama",
    description:
      "Local AI image generation system that strengthens weak prompts through an LLM powered enhancement layer before diffusion inference. Built with FastAPI, llama.cpp, and diffusers to combine local model serving, prompt refinement, and modular backend orchestration without relying on hosted APIs.",
    tags: [
      { name: "FastAPI", color: "text-green-600" },
      { name: "llama.cpp", color: "text-purple-600" },
      { name: "Local Serving", color: "text-orange-500" },
      { name: "Diffusers", color: "text-blue-600" },
    ],
    categories: ["AI", "Backend", "ML Systems"],
    featured: true,
    image: text_to_image,
    image_webp: text_to_image_webp,
    metric: "100% local inference",
    source_code_link: "https://github.com/vineetagarwal54/text_to_image_llama",
  },
  {
    name: "Terrapin Events - Campus Event Management",
    description:
      "Full stack campus event platform built by a team using React, FastAPI, and MongoDB, with CAS SSO, JWT role based access control, Stripe payments, and waitlist automation. Deployed on Kubernetes with CI/CD and reliability focused testing, holding sub 200ms API performance under 100+ concurrent users.",
    tags: [
      { name: "React", color: "text-blue-600" },
      { name: "FastAPI", color: "text-green-600" },
      { name: "Kubernetes", color: "text-purple-600" },
      { name: "MongoDB", color: "text-orange-600" },
    ],
    categories: ["Full Stack", "Backend", "Cloud"],
    featured: true,
    image: terrapinEvents,
    image_webp: terrapinEvents_webp,
    metric: "Sub 200ms at 100+ users",
    source_code_link:
      "https://github.com/bhavnakumari/enpm613-team4-terrapin-events",
  },
  {
    name: "Plywood Studio AI Chatbot",
    description:
      "AI powered customer support chatbot with business specific knowledge, a fallback model path, Redis caching, and a production style conversational interface. Built with FastAPI, OpenAI, and Hugging Face using a hybrid inference workflow that stays available offline.",
    tags: [
      { name: "FastAPI", color: "text-blue-700" },
      { name: "OpenAI", color: "text-green-600" },
      { name: "Redis", color: "text-pink-600" },
    ],
    categories: ["AI", "Backend", "Full Stack"],
    featured: false,
    image: aIChatbot,
    image_webp: aIChatbot_webp,
    source_code_link: "https://github.com/vineetagarwal54/AIChatbot",
  },
  {
    name: "CollabDraw",
    description:
      "Real time collaborative whiteboard with room based sessions, live drawing updates, WebSocket communication, PostgreSQL, and Prisma, organized in a structured monorepo. A clean example of frontend and backend coordination in real time systems.",
    tags: [
      { name: "Next.js", color: "text-blue-700" },
      { name: "TypeScript", color: "text-green-600" },
      { name: "WebSocket", color: "text-pink-600" },
    ],
    categories: ["Frontend", "Backend", "Full Stack", "Real Time"],
    featured: false,
    image: collabDraw,
    image_webp: collabDraw_webp,
    source_code_link: "https://github.com/vineetagarwal54/CollabDrawAI",
  },
  {
    name: "Job Tracker",
    description:
      "Electron desktop app that automates the messy process of saving postings and tracking applications across platforms. It scrapes job data and organizes deadlines, statuses, and follow ups in one workflow.",
    tags: [
      { name: "Electron", color: "text-blue-600" },
      { name: "Web Scraping", color: "text-teal-600" },
      { name: "Automation", color: "text-green-600" },
    ],
    categories: ["Desktop App", "Automation", "Full Stack"],
    featured: false,
    image: jobTracker,
    image_webp: jobTracker_webp,
    source_code_link: "https://github.com/vineetagarwal54/Job_Tracker",
  },
  {
    name: "MeetSpace",
    description:
      "Real time video conferencing app with React, TypeScript, Node.js, Express, and WebRTC, featuring chat, screen sharing, recording, and dynamic participant layouts. Strong proof of real time systems and peer to peer backend coordination.",
    tags: [
      { name: "React", color: "text-blue-700" },
      { name: "WebRTC", color: "text-green-600" },
      { name: "TypeScript", color: "text-pink-600" },
    ],
    categories: ["Frontend", "Backend", "Full Stack", "Real Time"],
    featured: false,
    image: MeetSpace,
    image_webp: MeetSpace_webp,
    source_code_link: "https://github.com/vineetagarwal54/MeetSpace",
  },
  {
    name: "Activity Logger",
    description:
      "Cross platform mobile app built with React Native, Node.js, and SQL for activity tracking and analytics. Included here as mobile proof inside a broader full stack profile rather than as a headline piece.",
    tags: [
      { name: "React Native", color: "text-blue-700" },
      { name: "Node.js", color: "text-green-600" },
      { name: "SQL", color: "text-pink-600" },
    ],
    categories: ["Mobile", "Full Stack", "Backend"],
    featured: false,
    image: ActivityLogger,
    image_webp: ActivityLogger_webp,
    source_code_link: "https://github.com/vineetagarwal54/ActivityLogger",
  },
];